[WIP]ASL datasets
sign-language-processing/datasets pull request #50
Opened 2024-01-18 10:25 UTC by J22Melody

2024-01-28 10:37 UTC, AmitMY requested changes
lgtm, just change to hosted poses

2024-01-28 10:37 UTC, AmitMY commented on sign_language_datasets/datasets/asl_citizen/asl_citizen.py
> +    "holistic": "/shares/volk.cl.uzh/zifjia/ASL_Citizen/poses",
hosted on gs://sign-language-datasets/poses/holistic/ASLCitizen.zip

2024-01-28 10:37 UTC, AmitMY commented on sign_language_datasets/datasets/asl_citizen/asl_citizen.py
> +                                # TODO: remove debug code
remove i guess

2024-04-08 14:06 UTC, J22Melody commented
@AmitMY could you merge this PR?

2024-04-09 19:36 UTC, AmitMY commented
merging without review.

2024-04-09 19:36 UTC, merged